apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example
spec:
  provider:
    gcpsm:
      projectID: stepin-dev-377209
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: asia-northeast3
          # name of the GKE cluster
          clusterName: dev-domain-cluster
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: stepin-dev-377209
          # reference the sa from above
          serviceAccountRef:
            name: team-a
            namespace: team-a