apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-backend          
  target:                                                             
    name: secret-to-be-created 
  data:                                                       
  - secretKey: .env
    remoteRef:            
      key: stage-play-webrtc